---
title: "ModelOutputs"
author: "Hannah Marchi"
date: "29 9 2021"
output: html_document
---


# Helmholtz
## two covariates

```{r, message = FALSE}
library(mgcv)
```

### all
```{r}
load("Workspaces/server/Original_all_x2_wrapper.RData")
rversion
```

#### Glm binomial
```{r}
summary(Original_all_x2$modelGlmBin)
Original_all_x2$qaplist$zeroGlm$xbin_1[2:4]
Original_all_x2$qaplist$zeroGlm$xbin_2[2:4]
```

#### Glm poisson
```{r}
summary(Original_all_x2$modelGlmPois)
Original_all_x2$qaplist$countGlm$xpois_1[2:4]
Original_all_x2$qaplist$countGlm$xpois_2[2:4]
```

#### Gam binomial
```{r}
summary(Original_all_x2$modelGamBin)
Original_all_x2$qaplist$zeroGam[[1]][2:4]
```

#### Gam poisson
```{r}
summary(Original_all_x2$modelGamPois)
Original_all_x2$qaplist$countGam[[1]][2:4]
rm(Original_all_x2)
```

### interd

#### Glm binomial
```{r}
load("Workspaces/server/Original_interd_x2.RData")
rversion
summary(Original_interd_x2$modelGlmBin)
Original_interd_x2$qaplist$zeroGlm$xbin_1[2:4]
Original_interd_x2$qaplist$zeroGlm$xbin_2[2:4]
```

#### Glm poisson
```{r}
summary(Original_interd_x2$modelGlmPois)
Original_interd_x2$qaplist$countGlm$xpois_1[2:4]
Original_interd_x2$qaplist$countGlm$xpois_2[2:4]
```

#### Gam binomial
```{r}
summary(Original_interd_x2$modelGamBin)
Original_interd_x2$qaplist$zeroGam[[1]][2:4]
```

#### Gam poisson
```{r}
summary(Original_interd_x2$modelGamPois)
Original_interd_x2$qaplist$countGam[[1]][2:4]
rm(Original_interd_x2)
```

### inst

#### Glm binomial
```{r}
load("Workspaces/server/Original_inst_x2.RData")
rversion
summary(Original_inst_x2$modelGlmBin)
Original_inst_x2$qaplist$zeroGlm$xbin_1[2:4]
Original_inst_x2$qaplist$zeroGlm$xbin_2[2:4]
```

#### Glm poisson
```{r}
summary(Original_inst_x2$modelGlmPois)
Original_inst_x2$qaplist$countGlm$xpois_1[2:4]
Original_inst_x2$qaplist$countGlm$xpois_2[2:4]
```

#### Gam binomial
```{r}
summary(Original_inst_x2$modelGamBin)
Original_inst_x2$qaplist$zeroGam[[1]][2:4]
```

#### Gam poisson
```{r}
summary(Original_inst_x2$modelGamPois)
Original_inst_x2$qaplist$countGam[[1]][2:4]
rm(list = ls())
```
